### ISSUE TITLE
Why use resolveDeps(covistra-admin) when module is not a dependency?

### ISSUE THREAD

**Issue by lpcarignan** [Covistra/hapi-plugin-covistra-security#3]
In the file index.js, the covistra-security module states its dependencies as followed on line 20:

`exports.deps = ['covistra-system', 'covistra-mongodb'];`

Later on, at line 74, registration of the module wants to resolve a dependency on the covistra-admin module:

`resolveDeps('covistra-admin').then(function(adminPlugin) {`

But if covistra-admin isn't a dependency of covistra-security, as stated on line 20, then why should we wait for it?

Also, shouldn't the call `next()` be inside the `then()` or `catch()`, thus preventing the overall framework of moving on to the next module to register without finishing registring correctly covistra-security.

And where is covistra-admin on the [homepage](https://github.com/Covistra) of the list of projects?

**Comment by jgrenon** [comment]
Let me  have a look, these are relatively old modules I shared awhile ago. I'll take time to answer your question tomorrow.

**Comment by jgrenon** [comment]
The reason is that 'covistra-admin' is an optional dependency and no admin interface will be create if it's not found.  Actually, we don't wait for it and this is why the `next` method is not linked to the result of the admin interface loading promise. 

As for covistra-admin, it's not published. 

I would advise that you fork and adjust all dependencies as this is using an obsolete version of Hapi. I'm not using Hapi anymore, so that's why I haven't really maintain these for a while. But I can answer questions if you want to migrate it for your own needs. I can even look if I can find covistra-admin somewhere and publish it. Not sure if it was complete, but could be a good foundation to easily produce admin CRUDs.

**Comment by lpcarignan** [comment]
Thank you @jgrenon for your answer. It gave me the opportunity to dig deeper into this as we have performance issues and `covistra-system` was on our list of culprits.

If we go back to line 74 of `index.js` where it calls `resolveDeps`, this then takes us to the file `lib/resolve_deps.js` under the `covistra-system` package. I've copy/pasted the major part of this file here so you could follow along my train of thoughts.

```
var promise = new P(function(resolve) {

            function checkDeps() {
                log.trace("Checking if plugin %s is available", name);
                if(server.plugins[name]) {
                    log.trace("Plugin %s has been loaded. Resolving it!", name);
                    resolve(server.plugins[name]);
                }
                else {
                    log.trace("Plugin %s is still not available. Waiting another 100ms", name);
                    timer = setTimeout(checkDeps, 100);
                }
            }

            if(server.plugins[name]) {
                log.trace("Plugin %s is already loaded, resolving it right now", name);
                resolve(server.plugins[name]);
            }
            else {
                log.trace("Plugin %s is not available. Waiting 100ms for it", name);
                timer = setTimeout(checkDeps, 100);
            }

        });

        promise.finally(function() {
            log.trace("Cleaning up plugin %s resolution timer", name);
            if(timer) {
                clearTimeout(timer);
            }
        });

        return promise.timeout(checkDepsTimeout);
```
If we look at this code inside the promise, this part of the code gets execute first because `covistra-admin` doesn't exists:

```
else {
                log.trace("Plugin %s is not available. Waiting 100ms for it", name);
                timer = setTimeout(checkDeps, 100);
}
```

The code waits for 100 ms before calling `checkDeps` which basically does the same thing. Since `covistra-admin` doesn't exists, it will timeout indefinitely. I've tested this code by changing the log level and indeed prints the log.trace continuously.

I wanted to bring this to your attention to see if I was on the right track. If your package is being used by other companies where you might have advice them of using `covistra-system` and `covistra-security`, it could be a good idea to notify them about this infinite loop for production code.

**Comment by jgrenon** [comment]
`return promise.timeout(checkDepsTimeout);` should force the promise to timeout after `checkDepsTimeout` ms. Maybe `checkDepsTimeout` is 0 in your code? Just put something like 5000 and the loop will complete after 5 seconds, if the deps is not resolved by then.

**Comment by lpcarignan** [comment]
If we look at `lib/resolve_deps.js` in `covistra-system`, we can see that` checkDepsTimeout` is set with the following value:

`var checkDepsTimeout = config.get('plugins:system:check_deps_timeout', 3000);`

I did print `checkDepsTimeout` with a `log.debug()` and saw 3000 as the value. 

I've included a log file showing how it just spins around forever. By looking at the timestamps on each line, I would be under the impression that it spins for more than 3000 ms: [logs.txt](https://github.com/Covistra/hapi-plugin-covistra-security/files/1644401/logs.txt)
 
The call `promise.timeout()` at the end does not work. I've looked for the log message in the `finally` part of the promise and it is nowhere to be found.

I'm still in the opinion that we should remove the check for `covistra-admin` in `index.js` of `covistra-security` and now, I would also review the code in `lib/resolve_deps.js` in `covistra-system` to make sure this infinite loop doesn't happen in other cases.

**Comment by jgrenon** [comment]
ok, I agree. the finally should be in the timeout chain and now it's just connected to the promise that does not expire. 

So the code should be 
```
let finalPromise = promise.timeout(checkDepsTimeout);
finalPromise.finally(function() {
            log.trace("Cleaning up plugin %s resolution timer", name);
            if(timer) {
                clearTimeout(timer);
            }
        });
return finalPromise;
```
This should ensure that finally is called when promise expires, thus canceling the 100ms timer, which, I agree, is problematic.

**Comment by lpcarignan** [comment]
I've tested your solution and it does work. After 3000 ms, I get the trace from the finally.

Thank you for your time resolving this issue.

**Comment by jgrenon** [comment]
Can you create a quick pull request please?
